config/routes.rb
Rails.application.routes.draw do
  
	root 'welcome#index'

	resources :users do 
		get :blogs, on: :member
	end
	resources :sessions
	resources :blogs

	namespace :admin do 

		root "users#index"

		resources :users do 
			collection do 
				get :search
			end
		end
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	validates :title, presence: { message: "标题不能为空" }
	validates :content, uniqueness: { message: "内容不能为空" }
	validates :user_id, presence: { message: "作者不能为空" }

	belongs_to :user
	# has_and_belongs_to_many :tags
	has_many :blogs_tags, class_name: "BlogsTags"
	has_many :tags, through: :blogs_tags

end

app/models/blogs_tags.rb
class BlogsTags < ApplicationRecord 

	self.table_name = "blogs_tags"

	# 模型校验
	validates_uniqueness_of :blog_id, scope: [:tag_id]

	belongs_to :blog
	belongs_to :tag

end

app/models/tag.rb
class Tag < ApplicationRecord
	validates :title, uniqueness: { message: "标签不能重复" }
	# has_and_belongs_to_many :blogs
	has_many :blogs_tags, class_name: "BlogsTags"
	has_many :blogs, through: :blogs_tags

end

app/models/user.rb
class User < ApplicationRecord
	validates :username, presence: { message: "用户名不能为空" }
	validates :username, uniqueness: { message: "用户名已经存在" }
	validates :password, presence: { message: "密码不能为空" }
	validates :password, length: {minimum: 6, message: "密码最短为6位数字" }

	has_many :blogs

	#自定义一个关联关系，用来查找公开的blog；
	has_many :public_blogs, -> { where(is_public: true) },
		class_name: "Blog"

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

	def index 
		@users = User.all
	end

	def search
		@users = User.all.where(["username like ?", "%#{params[:username]}%"])
		render action: :index
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include Concerns::UserSession

	private
	def auth_user 
		unless logged_in?
			flash[:notice] = "请先登录"
			redirect_to new_session_path
		end
	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :auth_user, except: [:index, :show]

	def index 
		@blogs = Blog.page(params[:page] || 1).per_page(params[:per_page] || 10).order("id desc").where(is_public: true).includes(:tags, :user) #指定在查询的时候把关联的tags和user查询出来
	end

	def show 
		@blog = Blog.find(params[:id])
	end

	def new 
		@blog = Blog.new
	end


	def edit 
		@blog = Blog.find(params[:id])
		render action: :new
	end

	def create 
		@blog = current_user.blogs.new(blog_attrs)
		@blog.user = current_user #这里的current_user是个方法，定义在concerns的user_sessions中
		if @blog.save 

			#保存标签
			update_tags

			flash[:notice] = "博客创建成功"
			redirect_to blogs_path
		else
			flash[:notive] = "博客创建失败"
			render action: :new
		end
	end

	def update 
		@blog = Blog.find(params[:id])
		@blog.attributes = blog_attrs
		if @blog.save 
			@blog.tags.destroy_all
			update_tags

			flash[:notice] = "博客更新成功"
			redirect_to blogs_path
		else
			flash[:notive] = "博客更新失败"
			render action: :new
		end
	end

	def destroy 
		@blog = Blog.find(params[:id]);
		@blog.destroy;
		redirect_to blogs_path
	end

	#params参数校验
	private
	def blog_attrs
		params.require(:blog).permit(:title, :content, :is_public)
	end

	def update_tags 
		params[:tags].split(',').each do |tag| 
			one_tag = Tag.find_by(title: tag)
			one_tag = Tag.new(title: tag) unless one_tag

			@blog.tags << one_tag #多对多 —— 创建数据，中间的“<<”表示追加
		end
	end
end

app/controllers/concerns/user_session.rb
module Concerns 
	module UserSession 

		def self.included base 
			base.class_eval do 
				helper_method :logged_in?
				helper_method :current_user
			end
		end

		# 登录
		def signin_user user 
			session[:user_id] = user.id
		end

		# 退出登录
		def logout_user 
			session[:user_id] = nil
		end

		# 判断是否登录
		def logged_in? 
      		!!session[:user_id] #这里使用！！来返回一个布尔值 !nil == true => !!nil == false；
		end

		# 当前用户
		def current_user 
			if logged_in? 
      			@current_user ||= User.find(session[:user_id]) #等同于：@current_user = @current_user || User.find(session[:user_id])
      		else
      			nil
			end
		end

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
	def new 

	end

	def create 
		@user = User.find_by(username: params[:username], password: params[:password])
		if @user 
			signin_user @user
			flash[:notice] = "登录成功"
			redirect_to root_path
		else
			flash[:notice] = "用户名或密码不正确"
			render(action: :new) 
		end
	end

	def destroy 
		logout_user
		flash[:notice] = "退出成功"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
 class UsersController < ApplicationController

	before_action :auth_user, only: [:index] 
	
	def index 
		@users = User.page(params[:page] || 1).per_page(params[:per_page] || 10).order("id DESC")
	end
	
	def new 
		@user = User.new
	end

	def create
		@user = User.new(params.require(:user).permit(:username, :password))
		if @user.save
			flash[:notice] = "注册成功，请登录"
			redirect_to new_session_path
		else
			render action: :new
		end
	end

	def blogs 
		@blogs = current_user.blogs.page(params[:page] || 1).per_page(params[:per_page] || 10).order("id DESC")
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@user = if logged_in?
  		User.find session[:user_id]
  	else
  		nil
  	end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/users/_one_user.html.erb
<tr>
  <td> <%= user.id %> </td>
  <td> <%= user.username %> </td>
  <td>  </td>
</tr>

app/views/admin/users/index.html.erb
<h1> 后台管理 - 用户管理 </h1>
<div class="row search-block">
  <form action="<%= search_admin_users_path %>" method="GET">
    <span> 用户名： </span>
    <input type="text" name="username" />
    <input type="submit" name="搜索" />
  </form>
</div>
<div class="row">
  <div class="col-sm-12">
    <table class="table">
      <tr>
        <th> ID </th>
        <th> 用户名 </th>
        <th>  </th>
      </tr>
      <%= render partial: "one_user", collection: @users, as: :user %>
    </table>
  </div>
</div>

app/views/blogs/_blogs.html.erb
<table class="table">
  <tr>
    <th> ID </th>
    <th> 标题 </th>
    <th> 作者 </th>
    <th> 公开 </th>
    <th> 操作 </th>
  </tr>

 	<% @blogs.each do |blog| %>

  <tr>
    <td> <%= blog.id %> </td>
      <td> 
        <%= link_to blog.title, blog_path(blog) %> 
        <% blog.tags.each do |tag| %>
          <span class="badabe">
            <%= tag.title %>
          </span>
        <% end -%>
      </td>
    <td> <%= blog.user.username %> </td>
    <td>
      <% if blog.user == current_user %>
        <%= blog.is_public ? "显示" : "不显示" %>

        <%= link_to "编辑", edit_blog_path(blog) %>

      <% end -%>
    </td>
    <td>
      <%= form_tag(blog_path(blog), method: "delete") do %>
        <%= submit_tag("删除") %>
      <% end -%>
    </td>
  </tr>
		
 	<% end -%>
  
</table>

<%= will_paginate @blogs %>

app/views/blogs/index.html.erb
<h1>博客</h1>

<div>
	<%= link_to "创建博客", new_blog_path, { class: "btn btn-primary" } %>
	<% if logged_in? %>
		<%= link_to "我的博客",  blogs_user_path(current_user), { class: "btn btn-default" } %>
	<% end -%>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= render "blogs" %>
  </div>
</div>

app/views/blogs/new.html.erb
<h1><%= @blog.new_record? ? "创建" : "编辑" %>博客</h1>

<%= form_for @blog, url: (@blog.new_record? ? blogs_path : blog_path(@blog) ), method: (@blog.new_record? ? :post : :put) do |f| %>
  
  <div>
    <% if @blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@blog.errors.count, "error") %> : </h2>
     
        <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  
  <div class="form-group">
    <%= f.text_field :title, class: "form-control", placeholder: "标题" %>
  </div>
  <div class="form-group">
    <%= f.text_area :content, class: "form-control", placeholder: "内容" %>
  </div>
  <div class="form-group">
    <input type="text" name="tags" value="<%= @blog.tags.map(&:title).join(",") %>" />
    <small> 多个标签用逗号","分隔 </small>
  </div>
  <div class="form-group">
    <% [[true, "显示"], [false, "不显示"]].each do |public| %>
      <input 
        type="radio" 
        name="blog[is_public]" 
        value="<%= public.first %>" 
        <%= "checked" if @blog.is_public == public.first %>
      />
      <span> <%= public.last %> </span>
    <% end -%>
  </div>
  <button type="submit" class="btn btn-default">
    <%= f.submit "保存" %>
  </button>

<% end %>

app/views/blogs/show.html.erb
<h1>
	<%= @blog.title %>
</h1>

<div class="row">
	<div class="col-sm-5">
		<p>作者：<%= @blog.user.username %>,</p>
		<%= @blog.content %>
	</div>

	<div class="col-sm-7">
		
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>我的Circles</title>
	<%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  	<header class="top">
  		<nav class="navbar navbar-default">
		  <div class="container-fluid">
		  	<div class="navbar-header">
		      <a class="navbar-brand" href="#">Circles</a>
		    </div>
		    <div class="collapse navbar-collapse circle-nav" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		      	<li>
		      		<%= link_to "首页", root_path %>
		      	</li>
		      	<li>
		      		<%= link_to "博客", blogs_path %>
		      	</li>
		      	<li>
		      		<%= link_to "用户列表", users_path %>
		      	</li>
		      	<% if logged_in? %>
					<li>
						<%= link_to "#{current_user.username}, 退出", session_path(current_user.id), method: 'delete' %>
					</li>
				<% elsif %>
			        <li>
			        	<%= link_to "登录", new_session_path %>
			        </li>
		      	<% end %>
		      </ul>
		    </div>
		  </div>
		</nav>
  	</header>
	
	<div class="container circle-body">
		
		<% if flash[:notice] %>
			<div class="alert alert-info">
				<%= flash[:notice] %>
			</div>
		<% end %>
		
    	<%= yield %>
	</div>

  </body>
</html>

app/views/users/blogs.html.erb
<h1><%= current_user.username %>的博客</h1>

<div>
	<%= link_to "创建博客", new_blog_path, { class: "btn btn-default" } %>
	<%= link_to "我的博客",  blogs_user_path(current_user), { class: "btn btn-primary" } %>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= render "blogs/blogs" %>
  </div>
</div>

app/views/users/index.html.erb
<h1>用户列表</h1>
<div class="row">
	<div class="col-sm-12">
		<table class="table table-bordered">
			<tr>
				<th>ID</th>
				<th>用户</th>
				<th>  </th>
			</tr>
			<% @users.each do |user| %>
				<tr>
					<td>
						<%= user.id %>
					</td>
					<td>
						<%= user.username %>
					</td>
					<td>

					</td>
				</tr>	
			<% end %>
		</table>

		<%= will_paginate @users %>
	</div>
</div>

app/views/users/new.html.erb
<h1>用户注册</h1>

<%= form_for @user do |f| %>
  
  <div>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> : </h2>
     
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  
  <div class="form-group">
    <%= f.text_field :username, class: "form-control", placeholder: "用户名" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password, class: "form-control", placeholder: "密码" %>
  </div>
  <button type="submit" class="btn btn-default">
    <%= f.submit "注册" %>
  </button>
  <span>
    <%= link_to "登录", new_session_path %>
  </span>

<% end %>

app/views/welcome/index.html.erb
<h1>This is circles homepage</h1>
<% if @user %>
	<div>
		<span>欢迎您，</span>
		<span> 
			<%= @user.username %>
		</span>
	</div>
<% else %>
	<p>
		
	</p>
<% end %>